default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e5
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 10000
    use_recurrent: false
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

Zombox:
    max_steps: 1.5e7
    batch_size: 128
    buffer_size: 2048
    beta: 1.0e-2
    hidden_units: 256
    summary_freq: 60000
    time_horizon: 64
    num_layers: 2
    behavioral_cloning:
        demo_path: Project/Assets/Demonstrations/zombox.demo
        strength: 1
        steps: 150000
    reward_signals:
        gail:
            strength: 1
            gamma: 0.99
            encoding_size: 128
            demo_path: Project/Assets/Demonstrations/zombox.demo
        extrinsic:
            strength: 1.0
            gamma: 0.99
